# Generated by Django 5.2.11 on 2026-03-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("director", "Director"),
                    ("colonel_gs", "Colonel_GS"),
                    ("gso_1", "GSO-1"),
                    ("gso_2", "GSO-2"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
